### ISSUE TITLE
How much time cost for a 30X WGS sample

### ISSUE THREAD

**Issue by SaintBacchus** [hplp/BWA_HLS#1]
![image](https://user-images.githubusercontent.com/7404824/48325001-7d6ebb00-e66e-11e8-9827-fee77498ab32.png)

In your report, using FPGA will accelerate 10-100X than CPU.   
Can you share the accurate time cost(in seconds) of FPGA and CPU for us?

**Comment by smosanu** [comment]
For a single FPGA instance of _ksw_extend2_, the average round-trip duration for one test alignment
was 333ms, while for the CPU it was 54ms. This was measured with the _chrono_ library on the CPU side. Therefore, one instance alone on the FPGA is 6.14x slower than the CPU, since it both runs at a lower frequency (250MHz) and it involves sending the buffers to the FPGA via the PCIe/DRAM. The CPU performance can be matched with at least 6 _ksw_extend2_ instances on the FPGA.

The numbers on the slide are for 80 instances running in parallel on one/ eight FPGA(s).

**Comment by SaintBacchus** [comment]
Thx for share this.
